module.exports = {
  CPTNFGNM: { id: 'completion', text: '이수구분' },
  SBJTNM: { id: 'title', text: '과목명' },
  CLSS: { id: 'division', text: '분반' },
  PNT: { id: 'credit', text: '학점' },
  TM: { id: 'timePerWeek', text: '강의시간' },
  RPSTPROFNM: { id: 'professor', text: '담당교수' },
  OPENLECTFGNM: { id: 'method', text: '설강여부' },
  DAYTMCTNT: { id: 'schedule', text: '시간표' },
  VILROOMNOCTNT: { id: 'room', text: '강의실' },
  VLDFGNM: { id: 'verification', text: '인증구분' },
  SUSTCDNM: { id: 'department', text: '학과' },
  PUBCYN: { id: 'public', text: '공개여부' },
  NOPUBCRESNNM: { id: 'noPublic', text: '비공개사유' },
  LESSTMFGNM: { id: 'runningTime', text: '수업시간' },
  TLSNOBJFG: { id: 'target', text: '수강대상' },
  LTLANGFGNM: { id: 'language', text: '강의언어' },
  ALLWRCNT: { id: 'allPersonnel', text: '허용인원' },
  TLSNRCNT: { id: 'currentPersonnel', text: '수강인원' },
  LMTRCNT: { id: 'limitPersonnel', text: '수강정원' },
  SCORTRETFGNM: { id: 'evaluation', text: '평가구분' },
  FLDFGNM: { id: 'liberal', text: '교양구분' },
  FLDDETAFGNM: { id: 'detailLibaral', text: '교양상세' },
};
